### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by pixsiro** [Utzel-Butzel/react-virtual-keyboard#1]
Hi,

I have installed keyboard inside my react project with `npm install virtual-keyboard --save` command. Using parts of your code to include the keyboard inside my js page, javascript console give me the error:`Uncaught TypeError: Cannot read property 'toLowerCase' of undefined` in `jquery.js:7095`. 
I had no problem about importing inside my project not even define Keybord: this is  how I instantiate the object Keyboard: 
`<Keyboard
                                        value={ this.state.inputfield }
                                        name="inputfield"
                                        options={{
                                            type:"input",
                                            layout:"qwerty",
                                            autoAccept: true,
                                            alwaysOpen: false,
                                            appendLocally: true,
                                            color:"light",
                                            class:"sxcycx",
                                            }}
                                        onChange={this.onInputChanged}`
I also initialize the state of "inputfield" with `this.state = {
            inputfield: "Input field"
        };` inside the constructor and define the onInputChanged function like this:
`onInputChanged(newState) { this.setState({
            inputfield: newState
        });
    }`
Where I'm wrong?

**Comment by Utzel-Butzel** [comment]
Hi Pixsiro,

do you have a stack trace for me?
