### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by spiritedsnowcat** [Utzel-Butzel/react-virtual-keyboard#11]
**Versions** 
Node: v6.11.4
React: 16.0.0
jQuery: 3.2.1
jQuery UI: 1.12.1
Yarn: v1.2.1

**Problem**
The keyboard doesn't show by default, and when the text field it creates is touched or clicked on, it doesn't show. Then, when backspacing in that field, it returns the following error:

_Uncaught ReferenceError: jQuery is not defined
    at HTMLInputElement.<anonymous> (C:\Development\TestApp\node_modules\virtual-keyboard\dist\js\jquery.keyboard.js:863)
    at HTMLInputElement.dispatch (C:\Development\TestApp\node_modules\jquery\dist\jquery.js:5206)
    at HTMLInputElement.elemData.handle (C:\Development\TestApp\node_modules\jquery\dist\jquery.js:5014)_ 

**Setup**
I installed react-virtual-keyboard from the repository using the command: "yarn add https://github.com/Utzel-Butzel/react-virtual-keyboard.git" and "yarn rebuild-native-modules". When referencing the keyboard from react, I use "import Keyboard from 'react-virtual-keyboard';". I have the following code for testing the component:

`<Keyboard
                        name='keyboard'
                        value={m.first_name}
                        options={{
                            type:"input",
                            layout: "querty",
                            alwaysOpen: true,
                            usePreview: false,
                            useWheel: false,
                            stickyShift: false,
                            appendLocally: true,
                            color: "light",
                            updateOnChange: true,
                            initialFocus: true,
                            display: {
                            "accept" : "Submit"
                            }
                        }}
                        ref="testkeyboard"
                        />`

**Additional**
jQuery is tested working. Not sure why it's complaining about jQuery. When adding the onChange and onAccept event listeners, it also complains with "Unknown event handler property `onAccepted`". Any advice?

**Comment by hodgef** [comment]
Hello,
Please note that npm has an older release that the version on this git repository. Are you using the npm package or you cloned this repo?

**Comment by hodgef** [comment]
Hello, I'll look into this. Btw, as per README, the "accepted" callback is "onAccepted".

<Keyboard 
  ...
  onChange={this.onInputChanged}
  onAccepted={this.onInputSubmitted}
  ref={k => this.keyboard = k}
/>

onInputChanged = (data) => {
  this.setState({ input: data });
}

onInputSubmitted = (data) => {
  console.log("Input submitted:", data);
}

**Comment by spiritedsnowcat** [comment]
Thanks hodgef! I tried using onAccepted just like that with the added functions in react, but it didn't work for me. Maybe it's just jQuery? I'm not sure, but I'll try it again once we get things figured out. It's probably something I'm doing on my end, but I'm not sure what.

**Comment by hodgef** [comment]
Hello @garethwarry. The issue seems to be that your "layout" option is set to "querty". Does it work for you if you put in "qwerty"?

**Comment by spiritedsnowcat** [comment]
Yes! That fixed it. I suppose it just didn't register the layout and threw an exception up the chain. 
Thanks for the help! 👍
