### ISSUE TITLE
Element ref was specified as a string (keyboard) but no owner was set. 

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [Utzel-Butzel/react-virtual-keyboard#15]
Getting the following error when trying to use the keyboard with React 16

Uncaught Error: Element ref was specified as a string (keyboard) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).

Moving react to the peer dependecies and reinstalling the keyboard did not work

**Comment by hodgef** [comment]
This might be helpful:

> I finally resolved this by making an edit in my webpack setup to specifically state where to use the required version of react. Something similar to the following, with an alteration to the node modules path, will hopefully help some people:
> 
> `resolve: { alias: { 'react': path.resolve(__dirname, '../../node_modules', 'react') } }`

Source: https://github.com/JedWatson/react-select/issues/2025#issuecomment-349920421

**Comment by clem91** [comment]
@mariomurrent-softwaresolutions I have the same problem.You surely have the last version of react 16.2.0 and this package as a peerdependencie of react to 15.0.1. So you have two versions of react running at the same time and that why the message displays. @Utzel-Butzel  some updates?

**Comment by clementAC** [comment]
If you use yarn, in package.json

```
"resolutions": {
  "react": "^16.2.0",
  "react-dom": "^16.2.0"
}
```
assuming you use 16.2.0

**Comment by Utzel-Butzel** [comment]
I have added the solution from @clem91

**Comment by clementAC** [comment]
Wow thanks for your reactivity! Can you make a release for npm with your last changes? By the way great wrapper

**Comment by Utzel-Butzel** [comment]
Yes, it is as 1.0.2 on NPM. Can you please test it?

**Comment by clementAC** [comment]
It works! Thank you
