### ISSUE TITLE
Button hover events

### ISSUE THREAD

**Issue by strangemodern** [Utzel-Butzel/react-virtual-keyboard#18]
I'm attempting to add a mouseover function for all keys. I've seen [this issue](https://github.com/Mottie/Keyboard/issues/589), but cannot find the correct selector for all virtual-keyboard buttons.

Do you have any recommendations?

**Comment by geloescht** [comment]
The cleanest way to implement this would probably be inside the component. As we currently do not have this requirement, we have no plans to implement it soon. If someone can port the example from the issue you linked, this help would of course be appreciated. For example, we could have a property named "keyHoverTimeout" that, when set to any other value than zero, enables eye-tracker mode.

This would probably be the correct place to stick the code to:
https://github.com/Utzel-Butzel/react-virtual-keyboard/blob/master/lib/Keyboard.js#L69

**Comment by strangemodern** [comment]
Thanks @geloescht, I agree that the cleanest way would be inside the component. For now I've simply attached listeners to button elements via react virtual dom.
