### ISSUE TITLE
virtual keyboard with a payment form that is inside an iframe

### ISSUE THREAD

**Issue by mathur7** [Utzel-Butzel/react-virtual-keyboard#19]
I am trying to use this package for a React web app that uses Stripe to process payments and is going to be used inside a kiosk. I am noticing that there is no option to use the keyboard with existing input fields or fields that are not accessible because they are inside an iframe(stripe has an embeddable form that comes with the embeddable button). Is there a way to make this work with existing input fields inside an iframe?

**Comment by geloescht** [comment]
Probably not, as this package is meant to be used as a React component. I.e. you create the input element under as part of a React component tree, not outside your React root and not as part of dangerouslySetInnerHtml. However, it is based on mottie-keyboard and that should be usable on top of existing input elements. Please see https://mottie.github.io/Keyboard/
I am going to close this. If you think mottie-keyboard is unsuitable and this package should be rather used, please drop us a line.
