### ISSUE TITLE
Backspace doesn't work when hiding the preview field. 

### ISSUE THREAD

**Issue by cyber-gin** [Utzel-Butzel/react-virtual-keyboard#26]
I have hidden the preview field in CSS and suddenly the backspace button does not delete the last character. 
The OnChange function fires even when the backspace button gets pressed without altering the input and so I cannot write the backspace feature myself. Also the OnChange event has the inputed text reversed. A lot of weird bugs!

**Comment by Utzel-Butzel** [comment]
Hi @cyber-gin The project is outdated. Please use https://virtual-keyboard.js.org/react/ instead

**Comment by cyber-gin** [comment]
Hello  Thanks for the prompt response. I had not noticed the project was outdated. just Installed the newer version and it works great!

Closing now.
