### ISSUE TITLE
Typescript definition files

### ISSUE THREAD

**Issue by bsurai** [Utzel-Butzel/react-virtual-keyboard#3]
Hi.
I'd like to use react-virtual-keyboard with typescript. Do you have typescript definition file?

**Comment by bsurai** [comment]
Here is my typescript definition file. 
[react-virtual-keyboard.d.ts.zip](https://github.com/Utzel-Butzel/react-virtual-keyboard/files/1120354/react-virtual-keyboard.d.ts.zip)

**Comment by Utzel-Butzel** [comment]
Hi @bsurai I have commited your typescript file. Many thanks!

**Comment by bsurai** [comment]
The file isn't optimal but it works for me.
