### ISSUE TITLE
github.com/gaearon/react-hot-boilerplate

### ISSUE THREAD

**Issue by bsurai** [Utzel-Butzel/react-virtual-keyboard#7]
When you open `https://www.npmjs.com/package/react-virtual-keyboard`, there is reference to `github.com/gaearon/react-hot-boilerplate` instead of `github.com/Utzel-Butzel/react-virtual-keyboard`.

It have to be fixed to publish typescript definitions. Here is conversation between me and @sheetalkamat. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18517#discussion_r130676124

**Comment by Utzel-Butzel** [comment]
Hi Bsurai, I have updated the package.json
