### ISSUE TITLE
Element ref was specified as a string (keyboard) but no owner was set.

### ISSUE THREAD

**Issue by cklepeis** [Utzel-Butzel/react-virtual-keyboard#9]
In React v16 we see this error:

> invariant.js:42 Uncaught Error: Element ref was specified as a string (keyboard) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).
>     at invariant (invariant.js:42)
>     at coerceRef (react-dom.development.js:8579)
>     at createChild (react-dom.development.js:8833)
>     at reconcileChildrenArray (react-dom.development.js:9132)
>     at reconcileChildFibers (react-dom.development.js:9495)
>     at reconcileChildrenAtPriority (react-dom.development.js:10127)
>     at reconcileChildren (react-dom.development.js:10118)
>     at updateHostComponent (react-dom.development.js:10370)
>     at beginWork (react-dom.development.js:10609)
>     at performUnitOfWork (react-dom.development.js:12573)

We see a similar error when we revert to React v15.x

We followed the instructions verbatim and not sure what's causing this error. We are only running 1 version of React.

**Comment by geloescht** [comment]
Currently we have a hardcoded dependency on react 15, which probably should be a peerDependency. When you upgraded to React 16, NPM probably moved React 15 to react-virtual-keyboard's private node_modules, so that it is using that instead of the one in the top-level node_modules. Please check if your-project/node_modules/react-virtual-keyboard/node_modules/react exists, if it does, you have multiple installations of React.

**Comment by geloescht** [comment]
Please try removing node_modules/react-virtual-keyboard and reinstalling the latest master. Should be fixed by moving react to peerDependencies. You should receive a warning during installation if you try to use it with React 16. It might work though, you could help us by reporting your findings.

**Comment by cklepeis** [comment]
Thanks, I'll try it out. I have since modified Keyboard.jsx, and got it working with React 16.

**Comment by mariomurrent-softwaresolutions** [comment]
@geloescht  This does not work for me. I'm using react 16 and when I install the keyboard via npm it automatically installs react 15 into this folder ...

**Comment by cklepeis** [comment]
@mariomurrent-softwaresolutions I haven't worked on the React project where I did this in a while, but here's some info. I installed jQuery, and virtual-keyboard (v. 1.27.1-beta) via npm, then modified Keyboard.jsx (there are most likely issues in this code, but it served our purposes - we use Flow)

```
// @flow

import React from 'react';
// import ReactDOM from 'react-dom';
import jQuery from 'jquery';
import 'virtual-keyboard/dist/js/jquery.keyboard';

export type Props = {
  value: string,
  name: string,
  options: Object, // available options are here https://github.com/Mottie/Keyboard/wiki/Options
  type: string,
  onChange?: (event: SyntheticEvent<HTMLInputElement>) => void
};

class Keyboard extends React.Component<Props, Object> {
  static defaultProps = {
    value: '',
    name: '',
    options: {
      layout: 'qwerty',
      usePreview: false,
      appendLocally: true
    },
    type: 'input'
  }

  constructor(props: Props) {
    super(props);
    this.state = {
      value: props.value,
      className: 'keyboard-wrapper'
    };

    this.handleChange = this.handleChange.bind(this);
  }

  componentDidMount() {
    if (this.props.options.usePreview === false && this.keyboardDiv) {
      jQuery(this.keyboardDiv).on('keyboardChange', (event: Event, keyboard) => {
      // $FlowFixMe
        this.handleChange(event, keyboard.preview.value);
      });
    }
  }

  componentWillReceiveProps(nextProps: Props) {
    if (nextProps.value !== this.state.value) {
      this.setState({
        value: nextProps.value
      });
    }
  }

  shouldComponentUpdate(nextProps: Props, nextState: Object) {
    let isChanged = nextState !== this.state;

    if (!isChanged) {
      // don't compare other props just yet
      isChanged = this.props.name !== nextProps.name ||
        this.props.type !== nextProps.type;
    }

    return isChanged;
  }

  componentWillUnmount() {
    if (this.keyboardDiv) {
      jQuery(this.keyboardDiv).remove();
    }
  }

  // Attach keyboard to element
  addKeyboard(ref: ?HTMLDivElement) {
    if (ref && ref !== null) {
      this.keyboardDiv = ref;
      // $FlowFixMe
      jQuery(this.keyboardDiv).keyboard(this.props.options);
    }
  }

  keyboardDiv: ?HTMLDivElement;

  handleChange: (event: SyntheticEvent<HTMLInputElement>) => void;

  handleChange(event: SyntheticEvent<HTMLInputElement>) {
    if (this.props.onChange) {
      this.props.onChange(event);
    }
  }

  render() {
    let keyboard;

    if (this.props.type === 'input') {
      keyboard = <input ref={input => this.addKeyboard(input)} value={this.state.value} name={this.props.name} onChange={this.handleChange} />;
    } else if (this.props.type === 'textarea') {
      keyboard = <textarea ref={textarea => this.addKeyboard(textarea)} value={this.state.value} name={this.props.name} onChange={this.handleChange} />;
    } else {
      throw new Error('Invalid keyboard type. Must be input or textarea');
    }

    return (
      <div className={this.state.className}>{keyboard}</div>
    );
  }
}

export default Keyboard;

```

**Comment by mariomurrent-softwaresolutions** [comment]
@cklepeis Thank you very much for the answer. I don't know if I want to change the code in the library for production purpose ... I ended up including the jquery extension for my project.
